---
title: "Climatic data format and SPEI analysis"
output: html_notebook
---

#overview 
The climatic data and enhance vegetation index downloaded from Google earth engine were processed and analysed.

#package
```{r}
library(SPEI)
library(data.table)
library(tidyverse)# for pipe
library(stringr)
```


#step 1. data loading and formatting
```{r}
dt <- fread("rawdata/GLORIA_ERA5_monthly_1950_2024_04_30.csv")
dt <- dt[,`system:index`:=NULL][,.geo:=NULL]
t_dt <- melt(dt, id.vars=c("plot_id"),variable.name = "var",value.name="value")
t_dt[,year:=str_sub(var, start = 1, end = 4)][
  ,month:=str_sub(var,5,6)][
    ,var_name:=str_sub(var,8,str_count(var))
  ]
dt <- dcast(t_dt,year+month+plot_id~var_name,value.var = "value")

setnames(dt,c("plot_id",
              "potential_evaporation_sum",
              "temperature_2m",
              "total_precipitation_sum"),
         c("summit","PE","temp","precip"))
dt[,c("PE","temp","precip"):=.(PE*1000,temp-273.15,precip*1000)]
dt[,D:=precip+PE]
```



step 2. Calculated SPEI
```{r}
for (i in unique(dt$summit)){
  dt[summit==i,spei_3:=as.data.table(spei(D,3)$fitted)][
      summit==i,spei_12:=as.data.table(spei(D,12)$fitted)]
}
dt[,date:=as.Date(paste(year,month,1,sep="-"))]
##set the region code
dt[summit %in% c("SUN","YAT","SEN"),region:="DAS"][
  summit %in% c("JNJ","DSH","TSW"),region:="SYU"][
    summit %in% c("LIN","SMZ","ZNF"),region:="NAH"][
      summit %in% c("SMN","QSS","QNS"),region:="HQM"][
        summit %in% c("HUU","MIN","JIA"),region:="SAC"]
dt[,region:=factor(region,levels=c("DAS","SYU","NAH","HQM","SAC"))] 
dt[,summit:=factor(summit,levels=c("SUN","YAT","SEN",
                                    "JNJ","DSH","TSW",
                                    "LIN","SMZ","ZNF",
                                    "SMN","QSS","QNS",
                                    "HUU","MIN","JIA"))]

ggplot(dt[region=="DAS"],aes(x=date,y=spei_12,color=spei_12))+
  geom_col()+
  facet_grid(summit~.)
write.csv(dt,"result/weather_index_data.csv")
```
